// 左侧tap
export const TAP_LASER = "TAP_LASER";
export const TAP_P3D = "TAP_P3D";
export const TAP_CODE = "TAP_CODE";
export const TAP_SETTINGS = "TAP_SETTINGS";
export const TAP_BASIC = "TAP_BASIC";
export const TAB_WRITE_AND_DRAW = "TAB_WRITE_AND_DRAW";
export const TAP_DEBUG = "TAP_DEBUG";

// tool path渲染方式: line or point; default line
// 添加在gcode的第一行
export const TOOL_PATH_RENDER_METHOD_LINE = ';TOOL_PATH_RENDER_METHOD_LINE';
export const TOOL_PATH_RENDER_METHOD_POINT = ';TOOL_PATH_RENDER_METHOD_POINT';

// p3d
export const P3D_SLICE_START = 'P3D_SLICE_START';
export const P3D_SLICE_STATUS = 'P3D_SLICE_STATUS';

// serial port
export const SERIAL_PORT_ACTION_GET_ALL_PATHS = 'SERIAL_PORT_ACTION_GET_ALL_PATHS';
export const SERIAL_PORT_ACTION_GET_OPEN_PATH = 'SERIAL_PORT_ACTION_GET_OPEN_PATH';
export const SERIAL_PORT_ACTION_OPEN = 'SERIAL_PORT_ACTION_OPEN';
export const SERIAL_PORT_ACTION_CLOSE = 'SERIAL_PORT_ACTION_CLOSE';
export const SERIAL_PORT_ACTION_WRITE = 'SERIAL_PORT_ACTION_WRITE';

export const SERIAL_PORT_ON_GET_ALL_PATHS = 'SERIAL_PORT_ON_GET_ALL_PATHS';
export const SERIAL_PORT_ON_GET_OPEN_PATH = 'SERIAL_PORT_ON_GET_OPEN_PATH';
export const SERIAL_PORT_ON_INSERT = 'SERIAL_PORT_ON_INSERT';
export const SERIAL_PORT_ON_PULL_OUT = 'SERIAL_PORT_ON_PULL_OUT';
export const SERIAL_PORT_ON_OPEN = 'SERIAL_PORT_ON_OPEN';
export const SERIAL_PORT_ON_CLOSE = 'SERIAL_PORT_ON_CLOSE';
export const SERIAL_PORT_ON_ERROR = 'SERIAL_PORT_ON_ERROR';
export const SERIAL_PORT_ON_WRITE_ERROR = 'SERIAL_PORT_ON_WRITE_ERROR';
export const SERIAL_PORT_ON_WRITE_OK = 'SERIAL_PORT_ON_WRITE_OK';
export const SERIAL_PORT_ON_RECEIVED_LINE = 'SERIAL_PORT_ON_RECEIVED_LINE';
export const SERIAL_PORT_ON_WARNING = 'SERIAL_PORT_ON_WARNING';

// gcode sender
export const GCODE_SENDER_ACTION_START = 'GCODE_SENDER_ACTION_START';
export const GCODE_SENDER_ACTION_PAUSE = 'GCODE_SENDER_ACTION_PAUSE';
export const GCODE_SENDER_ACTION_RESUME = 'GCODE_SENDER_ACTION_RESUME';
export const GCODE_SENDER_ACTION_STOP = 'GCODE_SENDER_ACTION_STOP';
export const GCODE_SENDER_ACTION_GET_STATUS = 'GCODE_SENDER_ACTION_GET_STATUS';
export const GCODE_SENDER_ACTION_GET_PROGRESS = 'GCODE_SENDER_ACTION_GET_PROGRESS';

export const GCODE_SENDER_ON_WARNING = 'GCODE_SENDER_ON_WARNING'; //data: {msg}
export const GCODE_SENDER_ON_STATUS_CHANGE = 'GCODE_SENDER_ON_STATUS_CHANGE'; //data: {preStatus, curStatus, taskId}; status: idle, started, paused, stopping
export const GCODE_SENDER_ON_PROGRESS_CHANGE = 'GCODE_SENDER_ON_PROGRESS_CHANGE'; //data: {total, sent, taskId}

// tool path
export const TOOL_PATH_GENERATE_LASER = 'TOOL_PATH_GENERATE_LASER';
export const TOOL_PATH_GENERATE_WRITE_AND_DRAW = 'TOOL_PATH_GENERATE_WRITE_AND_DRAW';

// p3d config: material settings
export const P3D_CONFIG_MATERIAL_SETTINGS_FETCH = 'P3D_CONFIG_MATERIAL_SETTINGS_FETCH';
export const P3D_CONFIG_MATERIAL_SETTING_UPDATE = 'P3D_CONFIG_MATERIAL_SETTING_UPDATE';
export const P3D_CONFIG_MATERIAL_SETTING_DELETE = 'P3D_CONFIG_MATERIAL_SETTING_DELETE';
export const P3D_CONFIG_MATERIAL_SETTING_CLONE = 'P3D_CONFIG_MATERIAL_SETTING_CLONE';

// p3d config: print settings
export const P3D_CONFIG_PRINT_SETTINGS_FETCH = 'P3D_CONFIG_PRINT_SETTINGS_FETCH';
export const P3D_CONFIG_PRINT_SETTING_UPDATE = 'P3D_CONFIG_PRINT_SETTING_UPDATE';
export const P3D_CONFIG_PRINT_SETTING_DELETE = 'P3D_CONFIG_PRINT_SETTING_DELETE';
export const P3D_CONFIG_PRINT_SETTING_CLONE = 'P3D_CONFIG_PRINT_SETTING_CLONE';

//firmware upgrade
export const FIRMWARE_UPGRADE_START = 'FIRMWARE_UPGRADE_START';
export const FIRMWARE_UPGRADE_STEP_CHANGE = 'FIRMWARE_UPGRADE_STEP_CHANGE';

// front end position
export const FRONT_END_POSITION_MONITOR = 'FRONT_END_POSITION_MONITOR';

// code
export const CODE_PROJECT_EXTENSION = '.rsc'; //rotrics studio scratch project extension
